steps:
  - task: qetza.replacetokens.replacetokens-task.replacetokens@3
    displayName: 'Replace tokens in *.toml'
    inputs:
      rootDirectory: '$(Build.Repository.LocalPath)'
      targetFiles: |
         *.toml
      tokenPrefix: '#{' 
      tokenSuffix: '}'

  - task: ShellScript@2
    displayName: Build Solution
    inputs:
      scriptPath: '$(Build.Repository.LocalPath)/build.sh'
      failOnStandardError: false

  - task: CmdLine@2
    displayName: Run DB Migration and feed data
    inputs:
      script: ./TechChallengeApp updatedb
      workingDirectory: '$(Build.Repository.LocalPath)/dist'
      failOnStderr: false

  - task: Docker@2
    displayName: Build and Push an image to container registry
    inputs:
      command: buildAndPush
      repository: techchallengerepo
      Dockerfile: '$(Build.Repository.LocalPath)/Dockerfile'
      containerRegistry: techchallenge-app-acr-service-connection
      tags: latest

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: manifest'
    inputs:
      PathtoPublish: pipeline
      ArtifactName: pipeline
